version: '3'

services:
  redis:
    image: "redis:4.0"
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: "redis-server /usr/local/etc/redis/redis.conf"

  db:
    image: "mongo:3.6"
    restart: "always"
    expose:
      - "27017"
    ports:
      - "27017:27017"
    command: ["--config", "/etc/mongo.conf", "--bind_ip", "0.0.0.0", "--noauth"]
    volumes:
      - ./mongo.conf:/etc/mongo.conf
   